### ISSUE TITLE
Upload Manifest Changes

### ISSUE THREAD

**Issue by FelixMDM** [FelixMDM/cargopilot#31]
* Integrate manifest redirects
* Redesign the upload manifest button, some more confirmation would be nice and making it less clunky (as we've seen)

**Comment by nbatra22** [comment]
Things to fix
- Server termination after solution gets outputted. server needs to remain running.
- Upload manifest button below the choose file selection. 
- Print on the search bar the selected file 
- Upload file then goes to the load/unload or balance screen (this redirect is already implemented), the uploading manifest file selection just needs to go to the file uploaded successfully and proceed screen, which is also implemented. need to remove the pop-up of file uploaded successfully.
